version: "3"

services:

  gateway:
    image: $IMAGE_BASE/gateway:$IMAGE_TAG
    restart: unless-stopped
    ports:
      - ${PORT}:80
    environment:
      - BASE_PATH=${BASE_PATH}
      - PORTAL_PATH=${PORTAL_BASE_PATH-}
      - MIS_PATH=${MIS_BASE_PATH-mis}

  auth:
    image: $IMAGE_BASE/auth:$IMAGE_TAG
    restart: unless-stopped
    volumes:
      - /etc/hosts:/etc/hosts
      - ./config:/etc/scow
    environment:
      - BASE_PATH=${BASE_PATH}

  redis:
    image: redis:alpine
    restart: unless-stopped

  portal-server:
    image: $IMAGE_BASE/portal-server:$IMAGE_TAG
    restart: unless-stopped
    volumes:
      - "/etc/hosts:/etc/hosts"
      - "./config:/etc/scow"
      - "~/.ssh:/root/.ssh"
    profiles: [ "portal" ]

  portal-web:
    image: $IMAGE_BASE/portal-web-${PORTAL_IMAGE_POSTFIX-root}:$IMAGE_TAG
    restart: unless-stopped
    environment:
      - MIS_DEPLOYED=${MIS_DEPLOYED-false}
      - MIS_URL=${MIS_BASE_PATH-}
      - BASE_PATH=${BASE_PATH}
    volumes:
      - "/etc/hosts:/etc/hosts"
      - "./config:/etc/scow"
    profiles: [ "portal" ]

  db:
    image: mysql:8
    restart: unless-stopped
    volumes:
      - "db_data:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=${MIS_DB_PASSWORD-}
    profiles: [ "mis" ]

  mis-server:
    image: $IMAGE_BASE/mis-server:$IMAGE_TAG
    restart: unless-stopped
    environment:
      - DB_PASSWORD=${MIS_DB_PASSWORD-}
    volumes:
      - "/etc/hosts:/etc/hosts"
      - "./config:/etc/scow"
      - /root/.ssh:/root/.ssh
    profiles: [ "mis" ]

  mis-web:
    image: $IMAGE_BASE/mis-web-${MIS_IMAGE_POSTFIX-root}:$IMAGE_TAG
    restart: unless-stopped
    environment:
      - PORTAL_DEPLOYED=${PORTAL_DEPLOYED-false}
      - PORTAL_URL=${PORTAL_BASE_PATH-}
      - BASE_PATH=${BASE_PATH}
    volumes:
      - "./config:/etc/scow"
    profiles: [ "mis" ]

volumes:
  db_data:
